### PR TITLE
net/wireguard: import using correct mechanism

### PR DESCRIPTION
**Pull request by zx2c4**
Fixes issue #1.

### CODE REVIEW

**Comment by Dabug123** [comment]
Nice I'll test out after work thanks

**Comment by Dabug123** [comment]
decided to pick engstk thanks dont know im even gonna keep this in future

**Comment by zx2c4** [comment]
engstk is merging this too. He's already done it for his op5 branch.  Please merge this commit.

**Comment by zx2c4** [comment]
https://github.com/engstk/op3t/commit/a9745b43a757531c4b48b4771364220062d054c5

Can you pull this from engstk, please?

**Pull request closed without merging**
